/**
 * Dump every intermediate value of one search into test-data/, as readable text.
 *
 *   npm run trace                          # uses the default question
 *   npm run trace -- "your question here"
 *
 * The dev server must be running (`npm run dev`). Nothing here computes anything
 * itself — it calls /api/trace and formats what comes back, so what you read is
 * what the application actually did.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const BASE = process.env.TRACE_BASE_URL || 'http://localhost:3000'
// TRACE_OUT lets you keep several traces side by side, e.g. a working query
// and a near-miss, without one overwriting the other.
const OUT = join(process.cwd(), process.env.TRACE_OUT || 'test-data')

const QUESTION = process.argv.slice(2).join(' ').trim()
  || 'What happens to a message after it fails five times?'

const rule = (t) => `${'='.repeat(78)}\n${t}\n${'='.repeat(78)}\n`
const pad = (s, n) => String(s).padEnd(n)
const num = (v, w = 9) => String(v).padStart(w)

const res = await fetch(`${BASE}/api/trace`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ question: QUESTION, topK: 4 })
})
if (!res.ok) {
  console.error(`${res.status} ${res.statusText} — is \`npm run dev\` running?`)
  console.error((await res.text()).slice(0, 400))
  process.exit(1)
}
const t = await res.json()
await mkdir(OUT, { recursive: true })

const files = {}

/* ---------------------------------------------------------------- 00 · map */
files['00-README.txt'] =
`SEARCH TRACE — every intermediate value of one query
${'-'.repeat(78)}

Question : "${t.question}"
Provider : ${t.provider.id} (${t.provider.embeddingModel})
Index    : ${t.index.documents} documents -> ${t.index.chunks} chunks, ${t.index.dimensions} dimensions

Read the files in order:

  01-chunking.txt          a document is cut into retrievable pieces
  02-document-vector.txt   one piece becomes a list of numbers
  03-question-vector.txt   the question becomes a list of numbers, the same way
  04-ranking.txt           every piece scored against the question
  05-relevance-filter.txt  which scores are good enough to use
  06-prompt.txt            the literal text sent to the model
  07-answer.txt            what came back

  trace.json               the raw response, if you want the full vectors

Generated by: npm run trace
`

/* ------------------------------------------------------------ 01 · chunking */
{
  const s = t.stage1_chunking
  let out = rule(`STAGE 1 · CHUNKING — ${s.document}`)
  out += `\n${s.rawCharacters} characters of markdown  ->  ${s.chunksProduced} chunks\n\n`
  out += `${s.note}\n\n`
  for (const c of s.chunks) {
    out += `${'-'.repeat(78)}\n`
    out += `chunk ${pad(c.id, 26)} heading: ${c.heading}\n`
    out += `${c.characters} characters — this exact text is what gets embedded:\n${'-'.repeat(78)}\n`
    out += c.embeddedText + '\n\n'
  }
  files['01-chunking.txt'] = out
}

/* ----------------------------------------------------- 02 · document vector */
function vectorReport(v, { showAllSlots = false } = {}) {
  let out = ''
  out += `dimensions        ${num(v.dimensions)}\n`
  out += `non-zero slots    ${num(v.nonZeroCount)}   (${v.percentFilled}% of the vector)\n`
  out += `zero slots        ${num(v.zeroCount)}\n`
  out += `L2 magnitude      ${num(v.l2Magnitude)}   <- normalised to 1, so cosine == dot product\n`
  out += `distinct tokens   ${num(v.distinctTokens)}\n`
  out += `hash collisions   ${num(v.collisionCount)}   (two tokens sharing one slot)\n`
  out += `slot map verified ${num(String(v.slotMappingVerified))}   <- every token's slot is non-zero in the real vector\n`
  if (v.collisions.length) {
    out += `\ncollisions (first ${v.collisions.length}):\n`
    for (const c of v.collisions) out += `  slot ${num(c.slot, 5)} <- ${c.tokens.join(', ')}\n`
  }
  out += `\nTOKEN -> SLOT -> VALUE`
  out += `\n  slot = hash(token) % ${v.dimensions}. No vocabulary file, no lookup table.\n\n`
  out += `  ${pad('token', 30)}${pad('slot', 8)}value at that slot\n`
  out += `  ${'-'.repeat(60)}\n`
  for (const ts of v.tokenSlots) {
    out += `  ${pad(ts.token, 30)}${pad(ts.slot, 8)}${ts.valueAtSlot}\n`
  }
  const slots = showAllSlots ? v.allNonZeroSlots : v.strongestSlots
  out += `\nNON-ZERO SLOTS ${showAllSlots ? '(all)' : '(20 strongest by absolute value)'}\n\n`
  for (const s of slots) out += `  [${num(s.slot, 5)}] = ${s.value}\n`
  return out
}

{
  const s = t.stage2_documentVector
  let out = rule('STAGE 2 · ONE CHUNK BECOMES NUMBERS')
  out += `\nchunk    ${s.chunkId}\nsource   ${s.source} > ${s.heading}\n\n`
  out += `THE TEXT THAT GETS EMBEDDED\n${'-'.repeat(78)}\n${s.textThatGetsEmbedded}\n${'-'.repeat(78)}\n\n`
  out += `TOKENISATION\n${s.tokenisation.note}\n\n`
  out += `unigrams after stemming (${s.tokenisation.unigramsAfterStemming.length}):\n  `
  out += s.tokenisation.unigramsAfterStemming.join(' ') + '\n\n'
  out += `with bigrams added: ${s.tokenisation.totalTokensWithBigrams} tokens total\n\n`
  out += `THE VECTOR\n${'-'.repeat(78)}\n`
  out += vectorReport(s.vector)
  files['02-document-vector.txt'] = out
}

/* ----------------------------------------------------- 03 · question vector */
{
  const s = t.stage3_questionVector
  let out = rule('STAGE 3 · THE QUESTION BECOMES NUMBERS — the same way')
  out += `\nquestion  "${s.question}"\n\n`
  out += `unigrams after stemming (${s.tokenisation.unigramsAfterStemming.length}):\n  `
  out += s.tokenisation.unigramsAfterStemming.join(' ') + '\n\n'
  out += `all tokens incl. bigrams (${s.tokenisation.totalTokensWithBigrams}):\n  `
  out += s.tokenisation.allTokens.join(' ') + '\n\n'
  out += `THE VECTOR\n${'-'.repeat(78)}\n`
  out += vectorReport(s.vector, { showAllSlots: true })
  out += `\nNote how few slots are filled compared with a document chunk. A short\n`
  out += `question is a very sparse vector — which is exactly why a chunk that\n`
  out += `happens to share a few rare words scores well.\n`
  files['03-question-vector.txt'] = out
}

/* ------------------------------------------------------------- 04 · ranking */
{
  const s = t.stage4_ranking
  let out = rule('STAGE 4 · SCORE EVERY CHUNK')
  out += `\n${s.note}\n\n`
  out += `chunks scored   ${s.chunksScored}\n`
  out += `time            ${s.searchMs} ms\n`
  out += `hand-checked #1 ${s.handCheckedTopScore}   <- recomputed outside the search code\n\n`
  out += `${pad('rank', 6)}${pad('score', 10)}${pad('source > heading', 52)}shared words\n`
  out += `${'-'.repeat(110)}\n`
  for (const r of s.scoreboard) {
    const label = `${r.source.replace(/\.md$/, '')} > ${r.heading}`
    out += `${pad(r.rank, 6)}${pad(r.score.toFixed(4), 10)}${pad(label.slice(0, 50), 52)}${r.sharedTokens.join(' ')}\n`
  }
  files['04-ranking.txt'] = out
}

/* ------------------------------------------------------ 05 · relevance gate */
{
  const s = t.stage5_relevanceFilter
  let out = rule('STAGE 5 · IS ANY OF IT GOOD ENOUGH?')
  out += `\n${s.note}\n\n`
  out += `top score          ${s.topScore}\n`
  out += `absolute floor     ${s.absoluteFloor}\n`
  out += `relative floor     ${s.relativeFloor}\n`
  out += `effective cutoff   ${s.effectiveCutoff}   <- max of the two\n\n`
  out += `KEPT (${s.kept.length}) — these go into the prompt\n`
  for (const k of s.kept) out += `  [${k.marker}] ${k.score.toFixed(4)}  ${k.source} > ${k.heading}\n`
  out += `\nDROPPED (${s.dropped.length}) — retrieved, then discarded as too weak\n`
  for (const d of s.dropped) out += `        ${d.score.toFixed(4)}  ${d.source} > ${d.heading}\n`
  files['05-relevance-filter.txt'] = out
}

/* -------------------------------------------------------------- 06 · prompt */
{
  const s = t.stage6_prompt
  let out = rule('STAGE 6 · THE PROMPT — the literal payload the model receives')
  out += `\n${s.note}\n\n`
  out += `context     ${s.contextCharacters} characters\n`
  out += `whole prompt ${s.totalPromptCharacters} characters (~${s.approximateTokens} tokens)\n\n`
  for (const m of s.messages) {
    out += `${'-'.repeat(78)}\nrole: ${m.role}\n${'-'.repeat(78)}\n${m.content}\n\n`
  }
  files['06-prompt.txt'] = out
}

/* -------------------------------------------------------------- 07 · answer */
{
  const s = t.stage7_answer
  files['07-answer.txt'] = rule('STAGE 7 · THE ANSWER')
    + `\nprovider   ${s.providerId}\ngeneration ${s.generationMs} ms\n\n${s.text}\n`
}

files['trace.json'] = JSON.stringify(t, null, 2)

for (const [name, content] of Object.entries(files)) {
  await writeFile(join(OUT, name), content, 'utf8')
}

console.log(`\nQuestion: "${t.question}"\n`)
const rel = process.env.TRACE_OUT || 'test-data'
console.log(`Wrote ${Object.keys(files).length} files to ${rel}/`)
for (const name of Object.keys(files)) {
  console.log(`  ${rel}/${name}`)
}
console.log(`\nTop hit: ${t.stage4_ranking.scoreboard[0].source} > ${t.stage4_ranking.scoreboard[0].heading} (${t.stage4_ranking.scoreboard[0].score})`)
console.log(`Kept ${t.stage5_relevanceFilter.kept.length} of ${t.stage4_ranking.chunksScored} chunks, cutoff ${t.stage5_relevanceFilter.effectiveCutoff}\n`)
